//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pim2019_desk.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_aula_local
    {
        public int idAulaLocal { get; set; }
        public Nullable<int> fkSala { get; set; }
        public Nullable<int> fkTurmaAluno { get; set; }
        public Nullable<int> fkDiaSemana { get; set; }
    
        public virtual tb_dia_semana tb_dia_semana { get; set; }
        public virtual tb_sala tb_sala { get; set; }
        public virtual tb_turma_aluno tb_turma_aluno { get; set; }
    }
}
