//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pim2019_desk.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_sala()
        {
            this.tb_aula_local = new HashSet<tb_aula_local>();
        }
    
        public int idSala { get; set; }
        public int numeroSala { get; set; }
        public int capacidade { get; set; }
        public Nullable<int> fkAlfabeto { get; set; }
        public Nullable<int> fkTipoSala { get; set; }
        public Nullable<int> fkAndar { get; set; }
    
        public virtual tb_alfabeto tb_alfabeto { get; set; }
        public virtual tb_andar tb_andar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_aula_local> tb_aula_local { get; set; }
        public virtual tb_tipo_sala tb_tipo_sala { get; set; }
    }
}
