//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pim2019_desk.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_turma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_turma()
        {
            this.tb_aula_local = new HashSet<tb_aula_local>();
            this.tb_turma_aluno = new HashSet<tb_turma_aluno>();
        }
    
        public int idTurma { get; set; }
        public Nullable<int> fkSigla { get; set; }
        public Nullable<int> fkAlfabeto { get; set; }
        public Nullable<int> fkCampus { get; set; }
        public Nullable<int> fkCurso { get; set; }
        public Nullable<System.DateTime> anoInicio { get; set; }
        public Nullable<int> semestreInicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_aula_local> tb_aula_local { get; set; }
        public virtual tb_campus tb_campus { get; set; }
        public virtual tb_curso tb_curso { get; set; }
        public virtual tb_sigla tb_sigla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_turma_aluno> tb_turma_aluno { get; set; }
    }
}
